### PR TITLE
Fix typo: Separate <- Separate

### PR DESCRIPTION
**Pull request by rogeriopradoj**

### CODE REVIEW

**Comment by lornajane** [comment]
ok to test

**Comment by lornajane** [comment]
Thanks for taking the time to send us this patch!

**Comment by rogeriopradoj** [comment]
Hi, @lornajane , thank you all for maintaining this awesome project!

Here in São Paulo, Brazil, we try to use joind.in in all the events we need feedback (recents @phpsp and @vagrantsp).

As long as we here, any date for launching new version of the Joind.in website?

See ya!

**Comment by lornajane** [comment]
The new site is live at http://m.joind.in.  It will move to http://www.joind.in at some point, but we haven't quite met all our requirements for that yet.  You can use it at http://m.joind.in, some features are missing for event hosts and speakers, but feel free to promote the new URL for attendees.

**Pull request merged**
